In [1]:
# load data from .mat files and save as .npy files
import numpy as np
import scipy.io as sio
import os

In [2]:
# check the data from .mat files 
lap = sio.loadmat('lap.mat')['L']
L_comb = sio.loadmat('lapComb.mat')['LComb']

In [6]:
eigvals, eigvecs = np.linalg.eigh(L_comb)

In [5]:
L_comb

array([[ 0.52112947, -0.00327754, -0.00327754, ...,  0.        ,
         0.        ,  0.        ],
       [-0.00327754,  0.51457438, -0.00327754, ...,  0.        ,
         0.        ,  0.        ],
       [-0.00327754, -0.00327754,  0.56373754, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.55718245,
        -0.00327754, -0.00327754],
       [ 0.        ,  0.        ,  0.        , ..., -0.00327754,
         0.68172911, -0.00327754],
       [ 0.        ,  0.        ,  0.        , ..., -0.00327754,
        -0.00327754,  0.63256596]])

In [7]:
eigvals

array([-4.99108116e-16,  2.02003074e-01,  2.26332045e-01,  3.28244076e-01,
        3.42084436e-01,  3.46793270e-01,  3.49241056e-01,  3.50169064e-01,
        3.51048776e-01,  3.54182270e-01,  3.55921598e-01,  3.59726975e-01,
        3.61058249e-01,  3.64577388e-01,  3.69839096e-01,  3.70153150e-01,
        3.72200492e-01,  3.76697299e-01,  3.80195206e-01,  3.83156469e-01,
        3.86438296e-01,  3.89679083e-01,  3.92303064e-01,  3.94228617e-01,
        3.96071793e-01,  3.98984496e-01,  4.00379171e-01,  4.05667959e-01,
        4.06298249e-01,  4.10388917e-01,  4.11937402e-01,  4.13336202e-01,
        4.15978592e-01,  4.17253468e-01,  4.19469224e-01,  4.20485699e-01,
        4.21397045e-01,  4.23431342e-01,  4.24446431e-01,  4.25676545e-01,
        4.26579143e-01,  4.28569689e-01,  4.29565611e-01,  4.31058670e-01,
        4.32916617e-01,  4.33895881e-01,  4.36777199e-01,  4.37016246e-01,
        4.38019290e-01,  4.41663842e-01,  4.42303521e-01,  4.42506590e-01,
        4.42836364e-01,  

In [7]:
gs0 = sio.loadmat('aligned.mat')['Xa'].T

In [8]:
gs0.shape

(1190, 360)

In [ ]:
gs0

array([[0.57249495, 0.53327774, 0.45361525, ..., 0.32143264, 0.45989103,
        0.53779798],
       [0.48649599, 0.44683442, 0.46271301, ..., 0.47520791, 0.52238227,
        0.6354806 ],
       [0.41232856, 0.42546141, 0.3446094 , ..., 0.51692223, 0.46797813,
        0.55749099],
       ...,
       [0.50658725, 0.53475688, 0.42995892, ..., 0.68947331, 0.62169156,
        0.62245191],
       [0.50184877, 0.52863504, 0.47806296, ..., 0.46640526, 0.51131196,
        0.54995905],
       [0.51614136, 0.49595044, 0.47791578, ..., 0.42589363, 0.47003766,
        0.50570256]])